### ISSUE TITLE
UI-hearts - styling and hover states

### ISSUE THREAD

**Issue by jringenberg** [Generative-Transfer-Art/valenftines-client#21]
- once a UI heart is showing an address, it's style should match what it will be in the real NFT (i.e. `fill="#ffffff" stroke="black" stroke-width="5px"` with black text)
- on hover, the black outline and text become hot pink: `#FA0F95`
- complete svgs for those two states live here: https://discord.com/channels/874404443586719774/938823788974452736/941776284206395412
- similarly, on hover, the empty hearts (dashed outlines) get a fill of `#fff2f2`

**Comment by JFrankfurt** [comment]
fixed by 57d3f768030104c407cceb1ea203fc667ae6830d
